# Generated by Django 5.2.7 on 2026-05-12 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('password_protected', 'Password protected'), ('private', 'Private'), ('unlisted', 'Unlisted')], db_index=True, default='private', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionDesignSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(default='minimal', max_length=80)),
                ('layout_style', models.CharField(default='grid', max_length=80)),
                ('cover_style', models.CharField(default='full_bleed', max_length=80)),
                ('grid_style', models.CharField(default='masonry', max_length=80)),
                ('font_family', models.CharField(default='Inter', max_length=120)),
                ('primary_color', models.CharField(default='#111827', max_length=20)),
                ('show_filenames', models.BooleanField(default=False)),
                ('show_media_count', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionDownloadSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_download_enabled', models.BooleanField(default=True)),
                ('video_download_enabled', models.BooleanField(default=True)),
                ('single_photo_download_enabled', models.BooleanField(default=True)),
                ('full_gallery_download_enabled', models.BooleanField(default=True)),
                ('favorites_download_enabled', models.BooleanField(default=True)),
                ('download_pin_enabled', models.BooleanField(default=False)),
                ('download_pin_hash', models.CharField(blank=True, max_length=255)),
                ('allow_original_download', models.BooleanField(default=True)),
                ('allow_web_size_download', models.BooleanField(default=True)),
                ('allow_high_res_download', models.BooleanField(default=True)),
                ('web_size_px', models.PositiveIntegerField(default=2048)),
                ('high_res_size_px', models.PositiveIntegerField(default=3600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionPrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_password_enabled', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('is_client_access_enabled', models.BooleanField(default=False)),
                ('client_password_hash', models.CharField(blank=True, max_length=255)),
                ('require_email_to_view', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('allow_client_private_marking', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
