# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        ('folders', '0001_initial'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_covers', to='media_assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='collection',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectiondesignsettings',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_settings', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='collectiondownloadsettings',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_settings', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='collectionprivacysettings',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='collections.collection'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner', 'status'], name='collections_owner_i_3160a5_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner', 'sort_order'], name='collections_owner_i_15c783_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'slug'), name='uniq_collection_slug_owner_active'),
        ),
    ]
