# Generated by Django 5.2.7 on 2026-05-13 15:45

import apps.collections.models
import django.core.validators
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def populate_download_pins(registry, schema_editor):
    CollectionDownloadSettings = registry.get_model("collections", "CollectionDownloadSettings")

    for settings in CollectionDownloadSettings.objects.all():
        if not settings.download_pin:
            settings.download_pin = apps.collections.models.generate_download_pin()
        settings.download_pin_enabled = True
        settings.download_pin_hash = make_password(settings.download_pin)
        settings.save(update_fields=["download_pin", "download_pin_enabled", "download_pin_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondownloadsettings',
            name='download_pin',
            field=models.CharField(default=apps.collections.models.generate_download_pin, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Download PIN must be exactly 4 digits.')]),
        ),
        migrations.AlterField(
            model_name='collectiondownloadsettings',
            name='download_pin_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(populate_download_pins, migrations.RunPython.noop),
    ]
