# Generated by Django 5.2.7 on 2026-05-12 19:44

import apps.favorites.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(default='Favorites', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('locked', 'Locked'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('selection_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('share_token', models.CharField(default=apps.favorites.models.generate_share_token, max_length=64, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to='collections.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='media_assets.mediaasset')),
                ('favorite_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='favorites.favoritelist')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteListActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('item_added', 'Item added'), ('item_removed', 'Item removed'), ('note_updated', 'Note updated'), ('submitted', 'Submitted'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], max_length=40)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('favorite_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='favorites.favoritelist')),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='favoritelist',
            index=models.Index(fields=['collection', 'status'], name='favorites_f_collect_06d50f_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriteitem',
            constraint=models.UniqueConstraint(fields=('favorite_list', 'media_asset'), name='uniq_favorite_item'),
        ),
    ]
