# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('total_videos', models.PositiveIntegerField(default=0)),
                ('total_video_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('total_storage_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_original_storage_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_preview_storage_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_thumbnail_storage_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_collections', models.PositiveIntegerField(default=0)),
                ('total_folders', models.PositiveIntegerField(default=0)),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('total_favorite_lists', models.PositiveIntegerField(default=0)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('total_gallery_views', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
