# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_sets', '0001_initial'),
        ('collections', '0001_initial'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('r2_object_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.collection')),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_assets.mediaasset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_sets.collectionset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='media_uploa_owner_i_816a58_idx')],
            },
        ),
    ]
