# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_sets', '0001_initial'),
        ('collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('gif', 'GIF')], db_index=True, max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('display_filename', models.CharField(max_length=255)),
                ('original_file_key', models.CharField(db_index=True, max_length=500)),
                ('preview_file_key', models.CharField(blank=True, max_length=500)),
                ('thumbnail_file_key', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(max_length=120)),
                ('extension', models.CharField(max_length=20)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='uploading', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('is_cover_candidate', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='collections.collection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='collection_sets.collectionset')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAssetMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera_make', models.CharField(blank=True, max_length=120)),
                ('camera_model', models.CharField(blank=True, max_length=120)),
                ('lens', models.CharField(blank=True, max_length=160)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('aperture', models.CharField(blank=True, max_length=40)),
                ('shutter_speed', models.CharField(blank=True, max_length=40)),
                ('focal_length', models.CharField(blank=True, max_length=40)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('media_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='media_assets.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['owner', 'status'], name='media_asset_owner_i_46f9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['collection', 'sort_order'], name='media_asset_collect_e46161_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['set', 'sort_order'], name='media_asset_set_id_0449ff_idx'),
        ),
    ]
