# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_sets", "0002_initial"),
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_assets",
                to="collection_sets.collectionset",
            ),
        ),
    ]
