# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0002_allow_collection_level_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="preview_file_size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="thumbnail_file_size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
