# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('attempt_type', models.CharField(choices=[('collection_password', 'Collection password'), ('folder_password', 'Folder password'), ('client_password', 'Client password'), ('download_pin', 'Download PIN')], max_length=40)),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collections.collection')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collection', '-created_at'], name='gallery_acc_collect_1201c0_idx'), models.Index(fields=['folder', '-created_at'], name='gallery_acc_folder__4a511e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GallerySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('access_type', models.CharField(choices=[('guest', 'Guest'), ('client', 'Client'), ('owner_preview', 'Owner preview')], default='guest', max_length=30)),
                ('session_token_hash', models.CharField(db_index=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collections.collection')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder')),
            ],
            options={
                'indexes': [models.Index(fields=['session_token_hash', 'expires_at'], name='gallery_acc_session_65c98b_idx')],
            },
        ),
    ]
