# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_sets', '0001_initial'),
        ('collections', '0001_initial'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionset',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='collections.collection'),
        ),
        migrations.AddField(
            model_name='collectionset',
            name='cover_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_covers', to='media_assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='setstats',
            name='set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='collection_sets.collectionset'),
        ),
        migrations.AddIndex(
            model_name='collectionset',
            index=models.Index(fields=['collection', 'sort_order'], name='collection__collect_d53503_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('collection', 'slug'), name='uniq_set_slug_collection_active'),
        ),
    ]
