# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0002_initial'),
        ('favorites', '0001_initial'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_email', models.EmailField(blank=True, max_length=254)),
                ('download_type', models.CharField(choices=[('single_original', 'Single original'), ('single_web_size', 'Single web size'), ('single_high_res', 'Single high res'), ('gallery_original_zip', 'Gallery original ZIP'), ('gallery_web_size_zip', 'Gallery web-size ZIP'), ('favorites_original_zip', 'Favorites original ZIP'), ('favorites_web_size_zip', 'Favorites web-size ZIP')], db_index=True, max_length=40)),
                ('download_quality', models.CharField(choices=[('original', 'Original'), ('high_res', 'High res'), ('web_size', 'Web size')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=20)),
                ('zip_file_key', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to='collections.collection')),
                ('favorite_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='favorites.favoritelist')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collection', 'status'], name='downloads_d_collect_2a5fe2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('download_type', models.CharField(max_length=40)),
                ('download_quality', models.CharField(max_length=20)),
                ('file_key_served', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='collections.collection')),
                ('favorite_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='favorites.favoritelist')),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collection', '-created_at'], name='downloads_d_collect_1e22c2_idx')],
            },
        ),
    ]
