# Generated by Django 5.2.7 on 2026-05-12 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_password_enabled', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_covers', to='media_assets.mediaasset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'sort_order'], name='folders_fol_owner_i_25e226_idx'), models.Index(fields=['owner', 'slug'], name='folders_fol_owner_i_16ee23_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'slug'), name='uniq_folder_slug_owner_active')],
            },
        ),
    ]
